### ISSUE TITLE
Error happen when running smoke_tests.py: object has no attribute 'name'

### ISSUE THREAD

**Issue by imsheridan** [tobegit3hub/miniflow#5]
Sorry maybe a naive question/ false issue since I touch miniflow the first time and try to study it and wants to help contribute.
Tried to run smoke_tests.py under the tests folder but encountered below issue. Is this due to running it in incorrect way? Or the op ".name"is not supported by miniflow currently.

> Hello, MiniFlow!
> 42
> 42.0
> Traceback (most recent call last):
>   File "smoke_tests.py", line 43, in <module>
>     main()
>   File "smoke_tests.py", line 38, in main
>     print(sess.run(c, feed_dict={a.name: 10.0}))
> AttributeError: 'PlaceholderOp' object has no attribute 'name'

**Comment by tobegit3hub** [comment]
Thanks @imsheridan .

The attribute 'name' is added recently. Can you try again after `pip install --upgrade miniflow`?

**Comment by imsheridan** [comment]
Yeah tried to upgrade it but the issue still persist. Is there any suggestion to debug this issue next step? :) Thanks.
C:\Users\xxx\Workspace\miniflow\tests>python --version
Python 2.7.10

C:\Users\xxx\Workspace\miniflow\tests>pip list
miniflow (0.2.8)

C:\Users\xxx\Workspace\miniflow\tests>python smoke_tests.py
Hello, MiniFlow!
42
42.0
Traceback (most recent call last):
  File "smoke_tests.py", line 43, in <module>
    main()
  File "smoke_tests.py", line 38, in main
    print(sess.run(c, feed_dict={a.name: 10.0}))
AttributeError: 'PlaceholderOp' object has no attribute 'name'

**Comment by tobegit3hub** [comment]
Sorry about that. This is fixed in `miniflow 0.2.9`. Please try upgrade like this.

```
pip install --upgrade 'miniflow>=0.2.9'
```

**Comment by imsheridan** [comment]
Yes, it works after upgraded to 0.2.9
Thanks @tobegit3hub

**Comment by tobegit3hub** [comment]
You're so welcome. Thanks for your report 😃
